# Generated by Django 3.1.2 on 2021-03-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0003_tenders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenders',
            name='upload',
        ),
        migrations.AlterField(
            model_name='tenders',
            name='availibility',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='category',
            field=models.CharField(choices=[('construction', 'Construction'), ('medical', 'Medical'), ('oil and gas', 'Oil and Gas'), ('it', 'IT'), ('electrical', 'Electrical'), ('others', 'Others'), ('telecom', 'Telecom')], default='Construction', max_length=100),
        ),
    ]
