# Generated by Django 3.1.2 on 2021-03-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0004_auto_20210314_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenders',
            name='availibility',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='category',
            field=models.CharField(choices=[('it', 'IT'), ('electrical', 'Electrical'), ('medical', 'Medical'), ('telecom', 'Telecom'), ('oil and gas', 'Oil and Gas'), ('construction', 'Construction'), ('others', 'Others')], default='Construction', max_length=100),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='organization_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
