# Generated by Django 3.1.2 on 2021-03-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0005_auto_20210318_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenders',
            name='availibility',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='category',
            field=models.CharField(default='Construction', max_length=100),
        ),
    ]
