# Generated by Django 3.1.2 on 2021-03-19 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0006_auto_20210318_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='datePublished',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
