# Generated by Django 3.1.2 on 2021-03-24 16:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0007_tenders_datepublished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('no_of_days', models.IntegerField(default=0)),
                ('bidding_amount', models.IntegerField(default=0)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, null=True, region=None)),
            ],
        ),
        migrations.RenameField(
            model_name='tenders',
            old_name='datePublished',
            new_name='datepublished',
        ),
        migrations.AlterField(
            model_name='tenders',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, null=True, region=None),
        ),
    ]
