# Generated by Django 3.1.2 on 2021-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0008_auto_20210324_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='tender_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
