# Generated by Django 3.1.2 on 2021-03-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0009_auto_20210324_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='tender_id',
            new_name='tenderId',
        ),
    ]
