# Generated by Django 3.1.2 on 2021-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0010_auto_20210324_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenders',
            name='file_uploaded',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
